### ISSUE TITLE
JavaScript in 1 hour

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#10]
**[ ID ]** 8a2592f3-3c7d-49e3-9df5-033e44c2c374

**[ Submitter's Name ]** Daniele Scasciafratte
**[ Submitter's Twitter ]** @Mte90Net

**[ Space ]** demystify

**[ Format ]** learning-lab

### Description 
Discover the javascript world and what that they have to know to go deeper in that language.
With a comparison between JavaScript and jQuery we can see that three part of JS: DOM, Events and AJAX.

### Agenda 
The people see how works and they want to go deeper and start to hacking after the demonstration of the part of that language.
The old slide http://mte90.github.io/Talk-JavaScript-1-hour/ need a new fresh air and more examples but they show the basis of this language.

### Participants 
Around a table with their pc to try or for take notes.

### Outcome 
People what to learn and discover the opportunity of this language not only for hobby but also for their work.
An best of all discover how a website works so they can understand the importance of security and privacy in internet

**Comment by Mte90** [comment]
In the meantime I improved my talk adding comics initially to simplify developer logic and thoughts.
As I can see now works very well with non-javascript developers and for non-developers.

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
