### ISSUE TITLE
Why you need to join an Open Source community

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#11]
**[ ID ]** 7cfb9cc5-513f-4767-907a-fbea90fb5ac6

**[ Submitter's Name ]** Daniele Scasciafratte
**[ Submitter's Twitter ]** @Mte90Net

**[ Space ]** movement
**[ Secondary Space ]** demystify

**[ Format ]** demo, 20 minutes

### Description 
There are many people that contribute in many way in open source so why you need to join?
To feel a a part of a team? To discover new things? To get new skills? To improve your communication? All of them and many others.

### Agenda 
I show my experience in the Mozilla community as Rep, Participation leader, mentor, speaker, developer and also in WordPress community as contributor, translator, developer and recruiter. My experience also in other project that asked my help to start like WikiToLearn.

### Participants 
Follow my slides and voice so they have only to follow my speak.

### Outcome 
People that want to join and I case contact me to get more informations about specific communities or workflow.

**Comment by Mte90** [comment]
My ideas is to show the benefit for the improvements of the skills like group working, project manager, english improvements and also obviously the pleasure to meet in live with the people that join the same community.
I am also working on a paper about how to recruit new volunteers https://docs.google.com/document/d/1kg7CxZIyebsXEjXWxGKxov84NWgEm-eQ8FFFWC2AsJk/edit#

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
