### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#12]
**[ ID ]** 35263575-f723-465e-9e17-4e93ecb7597d

**[ Submitter's Name ]** Azharul Islam Azharul
**[ Submitter's Twitter ]** @azharul_sylhet

**[ Space ]** localisation
**[ Secondary Space ]** youth

**[ Format ]** format-not-sure

### Description 
Internet is a big sector in the world for know anything. And every body like to see that at his own language. And also he will understand anything very goodly by his own language. So, here localisation is a very good session.

### Agenda 
by users review and activities

### Participants 
I have no problem that how many participants are here. I will talk with them friendly and discuss about session like a group.

### Outcome 
I want to see a good and secure web, and almost a happy user by my and other participants activities.

**Comment by alicoding** [comment]
Can you give an example of what your session will be? Like will it be hacking session/ demo session or presentation?

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
