### ISSUE TITLE
Badge for all

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#13]
**[ ID ]** 4d4de436-8b26-4538-ae42-f27d6e2fedd3

**[ Submitter's Name ]** Giridhar Akarapu
**[ Submitter's Affiliated Organisation ]** Bike Shed
**[ Submitter's Twitter ]** @GiridharAkarapu

**[ Space ]** badges
**[ Secondary Space ]** youth

**[ Format ]** demo

### Description 
the open badges program is targeted to students mainly and the contributors , it should have a  great impact & core contributors must be recognized by these open badge should be helpful for them in all aspects , well it should be done with FSA'S & REP'S , there are many people who becomes rep and from their they stop their contributions to avoid this kind of situations open badge must be kept and to make mozilla more Big .

### Agenda 
it works great and the contribution of each and every person gets counted and valued , then badges would be given to them individually not once in a month , it makes a lot of contributors to contribute more and more  .

### Participants 
50

### Outcome 
The outcome after the festival would be more bigger because , it make a lot of interest in students and contributors to contribute more like organizing events in schools , colleges , corporate offices  and they will be getting badge from their mentors .

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
