### ISSUE TITLE
Smart City Hack-a-thon

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#14]
**[ ID ]** f60ecac2-1027-43c9-8682-05e728671c14

**[ Submitter's Name ]** Pravash Dey
**[ Submitter's Affiliated Organisation ]** The 1947- Technology Business Incubator (TBI)
**[ Submitter's Twitter ]** @Pravashdey

**[ Space ]** youth
**[ Secondary Space ]** exhibit

**[ Format ]** hands-on

### Description 
Digital India Hack-a-thon is about coding together to solve real world problems. Students, Developers, Entrepreneurs, Designers and Idea generators will come together to build amazing applications, in an effort to create world a better place. Participants will spend 48 hours building a solution to a problem they really want to solve.

Integrated throughout the day will be examples of disruptive ideas from around Gujarat and Pan India, many of which ‘Silicon Valley comes to India’ hasn't witnessed yet, as well as tips on taking the fear out of making the leap to entrepreneurship. Some leading mentors, technology experts/ trainers and  advisers will be on hand throughout the span of the event to answer your questions on challenges you’re facing. The areas we will cover: your business model, revenue model, social media and digital marketing strategy, selling to who and how, etc and there will be plenty of networking with other start-ups.

### Agenda 
Pre-hackathon workshop will provide relevant support to develop business ideas and skills. On the 1st day, the participants will receive guidance on the concept of the Ideation Model, MVP (minimum viable product) and Technical Guidance. The Hack-a-thon will be conducted on day 2 and 3.

### Participants 
In our previous hack-a-thon, held on 11th-12th April, approx. 90 participants had attended the event. At the end of the event, we had 13 working applications out of which the top 6 were selected.

### Outcome 
Our goal is to get developers, designers and entrepreneurs come together, form connections and apply their skills to create something of value. By creating a makerspace, creators are engaged and are able to collaborate to create a solution, on which they would go on to build a company. The hackathon will be in an intellectually stimulating environment that will spur innovation and collaboration.

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
