### ISSUE TITLE
Demolish the web with the Firefox Dev Tools

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#7]
**[ ID ]** 2cce4288-7cf8-464b-85e6-1a5f6e51dfd2

**[ Submitter's Name ]** Daniele Scasciafratte
**[ Submitter's Twitter ]** @Mte90Net

**[ Space ]** demystify 

**[ Format ]** 45 minute for a learning labs

### Description
Discover many unknown features of Firefox Developer Edition, with his tools and try it with cool examples!
It is a showcase of the developer tools of Firefox with demos and discover interesting features that you didn't know.

### Agenda
This is a little workshop that I do often in Italy and outside.
Many people after the workshop discover and learn the powerful of the Firefox Dev Tools.
Also they can see the difference with the tools of Chrome or other browser and switch to the Firefox developer edition

Slide: http://mte90.github.io/Talk-DevTools

### Participants
Very simple people around a table that follow my slides and try the stuff that I show the talk.

### Outcome
The next step of the talk that the people continue to use FF Dev Edition and follow the hacks blog to get update of the last features.

**Comment by Mte90** [comment]
Many people as designer or writer try to understand html but without the knowledge of tools it is very difficult, this talk can be simplified for that target with demo also of webmaker.

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
