### ISSUE TITLE
Gamification in WordPress for your community

### ISSUE THREAD

**Issue by mmmavis** [MozillaFoundation/mozfest-program-2016#9]
**[ ID ]** 0222bb6b-441f-40d7-905f-fa52b80516e3

**[ Submitter's Name ]** Daniele Scasciafratte
**[ Submitter's Twitter ]** @Mte90Net

**[ Space ]** movement
**[ Secondary Space ]** badges

**[ Format ]** learning-lab, 30 minutes

### Description 
We see the example of PassoPasso project used in the Italian community to the new volunteers to learn and join the community.
With a task based system with badge and mentoring we can power up your community.

### Agenda 
Gamification and independence is important in learning when it is done in internet.
A simple website with everything can improve the participation on your community only with a brainstorming of the most interesting activities with specific requirements!
In our case the project showed how many people can start and discover freely without a real human contact that happen after few task.

### Participants 
People that follow the slides and in case ask questions.

### Outcome 
Many people join the PassoPasso project (http://passopasso.mte90.net) working on the WordPress plugin DaTask and discover that the gamification can help the community for the first steps of a volunteer.

**Comment by Mte90** [comment]
We are working to the 2.0 version with a new interface and improve the social features, for october probably will be ready

**Comment by marcwalsh-zz** [comment]
Thanks for the submission! Unfortunately this session has not been selected as part of the program for 2016. Please expect an email from us with further information very soon.
